version: '2'
services:
    yolseapp-app:
        image: yolseapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://yolseapp-postgresql:5432/YolseApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    yolseapp-postgresql:
        extends:
            file: postgresql.yml
            service: yolseapp-postgresql
